version: "3.9"

services:
    loki:
        image: grafana/loki:2.9.0
        ports:
            - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml

    promtail:
        image: grafana/promtail:2.9.0
        volumes:
            - ./logs:/var/log
        command: -config.file=/etc/promtail/config.yml -print-config-stderr

    grafana:
        environment:
            - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        entrypoint:
            - sh
            - -euc
            - |
                mkdir -p /etc/grafana/provisioning/datasources
                cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
                apiVersion: 1
                datasources:
                - name: Loki
                  type: loki
                  access: proxy
                  orgId: 1
                  url: http://loki:3100
                  basicAuth: false
                  isDefault: true
                  version: 1
                  editable: false
                EOF
                /run.sh
        image: grafana/grafana:latest
        ports:
            - "3000:3000"

    backend:
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        volumes:
            - ./backend:/var/www/html
        ports:
            - "9000:80"
        environment:
            - LOKI_URL=http://loki:3100
            - LOKI_LOG_URI=loki/api/v1/push
        command:
            bash -c 'composer install && apache2-foreground'

    frontend:
        image: node:20.9
        environment:
            - NODE_ENV=development
        volumes:
            - ./frontend:/opt/node_app
        working_dir: /opt/node_app
        ports:
            - "3333:3000"
            # hmr port for hot reload (vite)
            - "24678:24678"
        command:
            bash -c 'npm install && npm run dev'

